#!/bin/bash
SENDER="./cmd/sender/"
RECEIVER="./cmd/receiver/"
if [[ $# -eq 0 ]] ; then
    echo "usage: $0 [sender|receiver|both|clean]"
fi

clean(){
    rm -f ./sender ./receiver
}

sender(){
    go build $SENDER
    go install $SENDER
    if [[ $? -ne 0 ]]; then
        echo "don't forget to set GOPATH. Check golang.org for more info"
    fi
}

receiver(){
    go build $RECEIVER
    go install $RECEIVER
    if [[ $? -ne 0 ]]; then
        echo "don't forget to set GOPATH. Check golang.org for more info"
    fi
}


both(){
    sender
    receiver
}

if [[ $1 = "sender" ]]; then
    sender
fi

if [[ $1 = "receiver" ]]; then
    receiver
fi

if [[ $1 = "both" ]]; then
    clean
    both
fi

if [[ $1 = "clean" ]]; then
    clean
fi
